export interface Product {
  id: string
  title: string
  author: string
  price: number
  originalPrice: number
  rating: number
  reviews: number
  image: string
  badge?: string
  category: string
  description: string
  publisher: string
  publishYear: number
  pages: number
  language: string
  isbn: string
  inStock: number
  tags: string[]
  isSet?: boolean
  setItems?: Product[]
}

export const categories = [
  "Tất cả",
  "Kinh tế - Kinh doanh",
  "Văn học",
  "Kỹ năng sống",
  "Thiếu nhi",
  "Khoa học - Công nghệ",
  "Lịch sử",
  "Tâm lý học",
  "Triết học",
  "Ngoại ngữ",
  "Bộ sách",
]

const harryPotterBooks: Product[] = [
  {
    id: "hp1",
    title: "Harry Potter và Hòn đá Phù thủy",
    author: "J.K. Rowling",
    price: 89000,
    originalPrice: 120000,
    rating: 4.9,
    reviews: 1500,
    image: "/harry-potter-book-1.png",
    category: "Thiếu nhi",
    description: "Tập 1 của bộ truyện Harry Potter",
    publisher: "NXB Trẻ",
    publishYear: 2020,
    pages: 320,
    language: "Tiếng Việt",
    isbn: "978-604-1-11111-1",
    inStock: 25,
    tags: ["thiếu nhi", "phép thuật", "phiêu lưu"],
  },
  {
    id: "hp2",
    title: "Harry Potter và Phòng chứa Bí mật",
    author: "J.K. Rowling",
    price: 89000,
    originalPrice: 120000,
    rating: 4.8,
    reviews: 1400,
    image: "/harry-potter-chamber-of-secrets.png",
    category: "Thiếu nhi",
    description: "Tập 2 của bộ truyện Harry Potter",
    publisher: "NXB Trẻ",
    publishYear: 2020,
    pages: 340,
    language: "Tiếng Việt",
    isbn: "978-604-1-11111-2",
    inStock: 25,
    tags: ["thiếu nhi", "phép thuật", "phiêu lưu"],
  },
  {
    id: "hp3",
    title: "Harry Potter và Tên tù nhân ngục Azkaban",
    author: "J.K. Rowling",
    price: 95000,
    originalPrice: 125000,
    rating: 4.9,
    reviews: 1300,
    image: "/harry-potter-book-3.png",
    category: "Thiếu nhi",
    description: "Tập 3 của bộ truyện Harry Potter",
    publisher: "NXB Trẻ",
    publishYear: 2020,
    pages: 380,
    language: "Tiếng Việt",
    isbn: "978-604-1-11111-3",
    inStock: 25,
    tags: ["thiếu nhi", "phép thuật", "phiêu lưu"],
  },
  {
    id: "hp4",
    title: "Harry Potter và Chiếc cốc lửa",
    author: "J.K. Rowling",
    price: 105000,
    originalPrice: 135000,
    rating: 4.8,
    reviews: 1200,
    image: "/harry-potter-goblet-of-fire.png",
    category: "Thiếu nhi",
    description: "Tập 4 của bộ truyện Harry Potter",
    publisher: "NXB Trẻ",
    publishYear: 2020,
    pages: 450,
    language: "Tiếng Việt",
    isbn: "978-604-1-11111-4",
    inStock: 25,
    tags: ["thiếu nhi", "phép thuật", "phiêu lưu"],
  },
  {
    id: "hp5",
    title: "Harry Potter và Hội Phượng hoàng",
    author: "J.K. Rowling",
    price: 115000,
    originalPrice: 145000,
    rating: 4.7,
    reviews: 1100,
    image: "/harry-potter-book-5.png",
    category: "Thiếu nhi",
    description: "Tập 5 của bộ truyện Harry Potter",
    publisher: "NXB Trẻ",
    publishYear: 2020,
    pages: 520,
    language: "Tiếng Việt",
    isbn: "978-604-1-11111-5",
    inStock: 25,
    tags: ["thiếu nhi", "phép thuật", "phiêu lưu"],
  },
  {
    id: "hp6",
    title: "Harry Potter và Hoàng tử lai",
    author: "J.K. Rowling",
    price: 115000,
    originalPrice: 145000,
    rating: 4.8,
    reviews: 1000,
    image: "/harry-potter-book-6.png",
    category: "Thiếu nhi",
    description: "Tập 6 của bộ truyện Harry Potter",
    publisher: "NXB Trẻ",
    publishYear: 2020,
    pages: 480,
    language: "Tiếng Việt",
    isbn: "978-604-1-11111-6",
    inStock: 25,
    tags: ["thiếu nhi", "phép thuật", "phiêu lưu"],
  },
  {
    id: "hp7",
    title: "Harry Potter và Bảo bối Tử thần",
    author: "J.K. Rowling",
    price: 125000,
    originalPrice: 155000,
    rating: 4.9,
    reviews: 1600,
    image: "/harry-potter-book-7.png",
    category: "Thiếu nhi",
    description: "Tập 7 của bộ truyện Harry Potter",
    publisher: "NXB Trẻ",
    publishYear: 2020,
    pages: 550,
    language: "Tiếng Việt",
    isbn: "978-604-1-11111-7",
    inStock: 25,
    tags: ["thiếu nhi", "phép thuật", "phiêu lưu"],
  },
]

export const products: Product[] = [
  {
    id: "1",
    title: "Đắc Nhân Tâm",
    author: "Dale Carnegie",
    price: 89000,
    originalPrice: 120000,
    rating: 4.8,
    reviews: 1250,
    image: "/dac-nhan-tam-book-cover.png",
    badge: "Bestseller",
    category: "Kỹ năng sống",
    description:
      "Đắc nhân tâm của Dale Carnegie là quyển sách nổi tiếng nhất, bán chạy nhất và có tầm ảnh hưởng nhất của mọi thời đại. Tác phẩm đã được chuyển ngữ sang hầu hết các thứ tiếng trên thế giới và có mặt ở hàng trăm quốc gia.",
    publisher: "NXB Tổng hợp TP.HCM",
    publishYear: 2020,
    pages: 320,
    language: "Tiếng Việt",
    isbn: "978-604-2-13456-7",
    inStock: 50,
    tags: ["kỹ năng sống", "giao tiếp", "thành công"],
  },
  {
    id: "2",
    title: "Sapiens: Lược sử loài người",
    author: "Yuval Noah Harari",
    price: 156000,
    originalPrice: 195000,
    rating: 4.9,
    reviews: 890,
    image: "/sapiens-book-cover.png",
    badge: "Mới",
    category: "Lịch sử",
    description:
      "Sapiens là một câu chuyện táo bạo về loài Homo sapiens - từ những khởi đầu khiêm tốn trong một góc xa xôi của châu Phi cho đến vị thế thống trị hành tinh ngày nay.",
    publisher: "NXB Thế Giới",
    publishYear: 2021,
    pages: 512,
    language: "Tiếng Việt",
    isbn: "978-604-2-23456-8",
    inStock: 30,
    tags: ["lịch sử", "nhân loại", "tiến hóa"],
  },
  {
    id: "3",
    title: "Atomic Habits",
    author: "James Clear",
    price: 135000,
    originalPrice: 180000,
    rating: 4.7,
    reviews: 2100,
    image: "/atomic-habits-inspired-cover.png",
    badge: "Hot",
    category: "Kỹ năng sống",
    description:
      "Atomic Habits sẽ định hình lại cách bạn nghĩ về tiến bộ và thành công, đồng thời cung cấp cho bạn các công cụ và chiến lược để biến đổi thói quen.",
    publisher: "NXB Thế Giới",
    publishYear: 2020,
    pages: 368,
    language: "Tiếng Việt",
    isbn: "978-604-2-33456-9",
    inStock: 25,
    tags: ["thói quen", "thành công", "phát triển bản thân"],
  },
  {
    id: "4",
    title: "Tôi Tài Giỏi, Bạn Cũng Thế",
    author: "Adam Khoo",
    price: 67000,
    originalPrice: 89000,
    rating: 4.6,
    reviews: 756,
    image: "/toi-tai-gioi-ban-cung-the-cover.png",
    badge: "Sale",
    category: "Kỹ năng sống",
    description:
      "Cuốn sách này sẽ giúp bạn khám phá tiềm năng vô hạn của bản thân và học cách khai thác nó một cách hiệu quả nhất.",
    publisher: "NXB Tổng hợp TP.HCM",
    publishYear: 2019,
    pages: 280,
    language: "Tiếng Việt",
    isbn: "978-604-2-43456-0",
    inStock: 40,
    tags: ["học tập", "thành công", "động lực"],
  },
  {
    id: "5",
    title: "Nhà Giả Kim",
    author: "Paulo Coelho",
    price: 79000,
    originalPrice: 99000,
    rating: 4.5,
    reviews: 1800,
    image: "/nha-gia-kim-cover.png",
    badge: "Bestseller",
    category: "Văn học",
    description:
      "Nhà giả kim là một câu chuyện về Santiago, một cậu bé chăn cừu trẻ tuổi đã dám theo đuổi giấc mơ của mình.",
    publisher: "NXB Hội Nhà Văn",
    publishYear: 2020,
    pages: 224,
    language: "Tiếng Việt",
    isbn: "978-604-2-53456-1",
    inStock: 60,
    tags: ["văn học", "triết lý", "cuộc sống"],
  },
  {
    id: "6",
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    price: 189000,
    originalPrice: 220000,
    rating: 4.4,
    reviews: 650,
    image: "/thinking-fast-slow-cover.png",
    category: "Tâm lý học",
    description:
      "Cuốn sách khám phá hai hệ thống tư duy của con người: Hệ thống 1 (nhanh, trực giác) và Hệ thống 2 (chậm, logic).",
    publisher: "NXB Thế Giới",
    publishYear: 2021,
    pages: 624,
    language: "Tiếng Việt",
    isbn: "978-604-2-63456-2",
    inStock: 20,
    tags: ["tâm lý học", "tư duy", "quyết định"],
  },
  {
    id: "7",
    title: "Dế Mèn Phiêu Lưu Ký",
    author: "Tô Hoài",
    price: 45000,
    originalPrice: 60000,
    rating: 4.9,
    reviews: 2500,
    image: "/de-men-phieu-luu-ky-cover.png",
    badge: "Kinh điển",
    category: "Thiếu nhi",
    description:
      "Tác phẩm kinh điển của văn học thiếu nhi Việt Nam, kể về cuộc phiêu lưu của chú dế mèn thông minh và dũng cảm.",
    publisher: "NXB Kim Đồng",
    publishYear: 2020,
    pages: 180,
    language: "Tiếng Việt",
    isbn: "978-604-2-73456-3",
    inStock: 100,
    tags: ["thiếu nhi", "phiêu lưu", "văn học việt nam"],
  },
  {
    id: "8",
    title: "Clean Code",
    author: "Robert C. Martin",
    price: 299000,
    originalPrice: 350000,
    rating: 4.6,
    reviews: 420,
    image: "/clean-code-cover.png",
    category: "Khoa học - Công nghệ",
    description: "Hướng dẫn viết code sạch, dễ đọc và dễ bảo trì. Cuốn sách kinh điển cho các lập trình viên.",
    publisher: "NXB Thông tin và Truyền thông",
    publishYear: 2021,
    pages: 464,
    language: "Tiếng Việt",
    isbn: "978-604-2-83456-4",
    inStock: 15,
    tags: ["lập trình", "công nghệ", "kỹ thuật"],
  },
  {
    id: "9",
    title: "The Art of War",
    author: "Sun Tzu",
    price: 75000,
    originalPrice: 95000,
    rating: 4.3,
    reviews: 890,
    image: "/placeholder-51g55.png",
    badge: "Hết hàng",
    category: "Triết học",
    description: "Binh pháp Sun Tzu - Tác phẩm kinh điển về chiến lược và chiến thuật.",
    publisher: "NXB Văn học",
    publishYear: 2020,
    pages: 200,
    language: "Tiếng Việt",
    isbn: "978-604-2-93456-5",
    inStock: 0,
    tags: ["triết học", "chiến lược", "kinh điển"],
  },
  {
    id: "hp-set",
    title: "Bộ sách Harry Potter (7 tập)",
    author: "J.K. Rowling",
    price: 650000,
    originalPrice: 850000,
    rating: 4.9,
    reviews: 2800,
    image: "/placeholder-0e3az.png",
    badge: "Bộ sách",
    category: "Bộ sách",
    description: "Bộ sách Harry Potter đầy đủ 7 tập, bao gồm tất cả các cuộc phiêu lưu của cậu bé phù thủy nổi tiếng.",
    publisher: "NXB Trẻ",
    publishYear: 2020,
    pages: 2800,
    language: "Tiếng Việt",
    isbn: "978-604-1-11111-0",
    inStock: 15,
    tags: ["thiếu nhi", "phép thuật", "phiêu lưu", "bộ sách"],
    isSet: true,
    setItems: harryPotterBooks,
  },
  ...harryPotterBooks,
]

export function getProductById(id: string): Product | undefined {
  return products.find((product) => product.id === id)
}

export function getProductsByCategory(category: string): Product[] {
  if (category === "Tất cả") return products
  return products.filter((product) => product.category === category)
}

export function searchProducts(query: string): Product[] {
  const lowercaseQuery = query.toLowerCase()
  return products.filter(
    (product) =>
      product.title.toLowerCase().includes(lowercaseQuery) ||
      product.author.toLowerCase().includes(lowercaseQuery) ||
      product.tags.some((tag) => tag.toLowerCase().includes(lowercaseQuery)),
  )
}
